import {
  Plane,
  GraduationCap,
  Car,
  Home,
  HeartPulse,
  ShoppingBag,
  Laptop,
  Gift,
  Dumbbell,
  Briefcase,
  Wallet,
  PiggyBank,
  Smartphone,
  Baby,
  Gamepad2,
  Music,
  Utensils,
  Coins,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
export const GOAL_CATEGORIES: {
  label: string;
  value: string;
  icon: LucideIcon;
  bgColor: string;
  iconColor: string;
}[] = [
  {
    label: "Travel",
    value: "Travel",
    icon: Plane,
    bgColor: "bg-blue-100",
    iconColor: "text-blue-600",
  },
  {
    label: "Education",
    value: "Education",
    icon: GraduationCap,
    bgColor: "bg-purple-100",
    iconColor: "text-purple-600",
  },
  {
    label: "Vehicle",
    value: "Vehicle",
    icon: Car,
    bgColor: "bg-orange-100",
    iconColor: "text-orange-600",
  },
  {
    label: "Home",
    value: "Home",
    icon: Home,
    bgColor: "bg-green-100",
    iconColor: "text-green-600",
  },
  {
    label: "Health",
    value: "Health",
    icon: HeartPulse,
    bgColor: "bg-red-100",
    iconColor: "text-red-600",
  },
  {
    label: "Shopping",
    value: "Shopping",
    icon: ShoppingBag,
    bgColor: "bg-pink-100",
    iconColor: "text-pink-600",
  },
  {
    label: "Technology",
    value: "Technology",
    icon: Laptop,
    bgColor: "bg-cyan-100",
    iconColor: "text-cyan-600",
  },
  {
    label: "Gifts",
    value: "Gifts",
    icon: Gift,
    bgColor: "bg-rose-100",
    iconColor: "text-rose-600",
  },
  {
    label: "Fitness",
    value: "Fitness",
    icon: Dumbbell,
    bgColor: "bg-emerald-100",
    iconColor: "text-emerald-600",
  },
  {
    label: "Career",
    value: "Career",
    icon: Briefcase,
    bgColor: "bg-indigo-100",
    iconColor: "text-indigo-600",
  },
  {
    label: "Savings",
    value: "Savings",
    icon: PiggyBank,
    bgColor: "bg-teal-100",
    iconColor: "text-teal-600",
  },
  {
    label: "Emergency Fund",
    value: "Emergency Fund",
    icon: Wallet,
    bgColor: "bg-yellow-100",
    iconColor: "text-yellow-600",
  },
  {
    label: "Gadgets",
    value: "Gadgets",
    icon: Smartphone,
    bgColor: "bg-violet-100",
    iconColor: "text-violet-600",
  },
  {
    label: "Family",
    value: "Family",
    icon: Baby,
    bgColor: "bg-sky-100",
    iconColor: "text-sky-600",
  },
  {
    label: "Entertainment",
    value: "Entertainment",
    icon: Gamepad2,
    bgColor: "bg-fuchsia-100",
    iconColor: "text-fuchsia-600",
  },
  {
    label: "Music",
    value: "Music",
    icon: Music,
    bgColor: "bg-lime-100",
    iconColor: "text-lime-600",
  },
  {
    label: "Food",
    value: "Food",
    icon: Utensils,
    bgColor: "bg-amber-100",
    iconColor: "text-amber-600",
  },
  {
    label: "Other",
    value: "Other",
    icon: Coins,
    bgColor: "bg-gray-100",
    iconColor: "text-gray-600",
  },
];
